tinyMCE.init({
    mode: "exact",
    elements: "id_content",
    theme: "advanced",
    skin : "o2k7",
    skin_variant : "silver",
    height: "250",
    width: "800",
    relative_urls: false,
    language: "{{ language }}",
    directionality: "{{ directionality }}",
    spellchecker_languages : "{{ spellchecker_languages }}",
    spellchecker_rpc_url : "{{ spellchecker_rpc_url }}",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "center",
    theme_advanced_statusbar_location : "bottom",
    theme_advanced_resizing : true,
    plugins: "contextmenu,directionality,fullscreen,paste,preview,searchreplace,spellchecker,visualchars,wordcount,youtube,inlinepopups,vimeo",
    paste_auto_cleanup_on_paste : true,
    theme_advanced_buttons1 : "formatselect,|,bold,italic,underline,|,undo,redo,|,cleanup,|,bullist,numlist,|,link,unlink",
    theme_advanced_buttons2 : "justifyleft,justifycenter,justifyright,justifyfull,|,image,youtube,vimeo",
    theme_advanced_buttons3 : "",
    });
